# Multi-Indexing with a Stock dataset

<img src='stocks.JPG'>
<i>Image by AhmadArdity from <a href="https://pixabay.com/photos/business-stock-finance-market-1730089/">Pixabay</a></i>

Multi-indexing is an important feature of pandas that enables you to have multiple (two or more) index levels on an axis. 

We will only review some of the basics of multi-indexing to prepare you for future study on this advanced topic. As you have time, I would strongly encourage you to review the Pandas documentation for further advanced usage (https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html).

As in previous examples, we will provide you a simple, example dataset to explain a topic and then have you practice on a real-world dataset. This dataset represents the data from six stocks that were downloaded directly from Yahoo Finance.

In [2]:
# standard imports
import pandas as pd
import numpy as np

Let’s start with a simple example:

In [4]:
# create sample Series
data = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], 
                                            [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    0.360809
   2    0.895467
   3   -0.420889
b  1   -0.461034
   3   -0.474278
c  1    0.553915
   2    2.147504
d  2   -0.829477
   3    0.238162
dtype: float64

In [6]:
# partial indexing
data['b']

1   -0.461034
3   -0.474278
dtype: float64

In [8]:
# select b through d
data['b':'d']

b  1   -0.461034
   3   -0.474278
c  1    0.553915
   2    2.147504
d  2   -0.829477
   3    0.238162
dtype: float64

Note that this will not always work if the index is not sorted. You can use `sort_index()` to sort the index before indexing.

In [10]:
# select only b and d data
data[['b','d']]

b  1   -0.461034
   3   -0.474278
d  2   -0.829477
   3    0.238162
dtype: float64

You can also index from an inner level using `.loc`

In [14]:
# indexing from 'inner' level index
data.loc[:,1]

a    0.360809
b   -0.461034
c    0.553915
dtype: float64

You can easily rearrange the data into a DataFrame using the `unstack()` method.

In [16]:
# from Multi-Index Series to DataFrame
data.unstack()

          1         2         3
a  0.360809  0.895467 -0.420889
b -0.461034       NaN -0.474278
c  0.553915  2.147504       NaN
d       NaN -0.829477  0.238162

Notice the missing values added due to the lack of data for the respective row and column combination.

The opposite of `unstack()` is `stack()`.

In [18]:
# from Multi-Index Series to DataFrame back to Series
data.unstack().stack()

a  1    0.360809
   2    0.895467
   3   -0.420889
b  1   -0.461034
   3   -0.474278
c  1    0.553915
   2    2.147504
d  2   -0.829477
   3    0.238162
dtype: float64

#### Student Practice
Try to perform the following tasks on the `stock` dataset that you will import below. Then check your answers as I walk through the solutions.

**Exercise:** Import the `stock.csv` data to a DataFrame called `stock` and view the DataFrame. Make the 'Stock' and 'Date' columns a part of the index. See the Pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) for help.

In [22]:
### ENTER CODE HERE ###
stock = pd.read_csv('stock.csv', index_col=['Stock', 'Date'])
stock

                        Open         High          Low        Close  \
Stock Date
AMZN  9/28/2020  3148.850098  3175.040039  3117.169922  3174.050049
      9/29/2020  3175.389893  3188.260010  3132.540039  3144.879883
      9/30/2020  3141.139893  3212.879883  3133.989990  3148.729980
      10/1/2020  3208.000000  3224.000000  3172.000000  3221.260010
      10/2/2020  3153.629883  3195.800049  3123.000000  3125.000000
...                      ...          ...          ...          ...
WFC   9/22/2021    46.490002    47.689999    46.470001    47.080002
      9/23/2021    47.459999    48.169998    47.160000    47.799999
      9/24/2021    47.779999    48.570000    47.730000    47.919998
      9/27/2021    48.380001    48.939999    46.160000    47.560001
      9/28/2021    47.009998    47.020000    45.070000    45.830002

                   Adj Close    Volume
Stock Date
AMZN  9/28/2020  3174.050049   4224200
      9/29/2020  3144.879883   3495800
      9/30/2020  3148.729980   4896100
      10/1/2020  3221.260010   4971900
      10/2/2020  3125.000000   5613100
...                      ...       ...
WFC   9/22/2021    47.080002  29430700
      9/23/2021    47.799999  21852800
      9/24/2021    47.919998  20376800
      9/27/2021    47.560001  48916600
      9/28/2021    45.830002  31655841

[1518 rows x 6 columns]

In [36]:
stock.reset_index().Stock.value_counts()

Stock
AMZN    253
MSFT    253
AAPL    253
AMD     253
BAC     253
WFC     253
Name: count, dtype: int64

**Exercise:** Select the 'Close' column from the `stock` DataFrame and name it `ser`. View the Series and check the index.

In [24]:
### ENTER CODE HERE ###
ser = stock['Close']
ser

Stock  Date
AMZN   9/28/2020    3174.050049
       9/29/2020    3144.879883
       9/30/2020    3148.729980
       10/1/2020    3221.260010
       10/2/2020    3125.000000
                       ...
WFC    9/22/2021      47.080002
       9/23/2021      47.799999
       9/24/2021      47.919998
       9/27/2021      47.560001
       9/28/2021      45.830002
Name: Close, Length: 1518, dtype: float64

**Exercise:** Select only the `AAPL` information from `ser` and save this as a variable called `apple`.

In [38]:
### ENTER CODE HERE ###
apple = ser['AAPL']
apple

Date
9/28/2020    114.959999
9/29/2020    114.089996
9/30/2020    115.809998
10/1/2020    116.790001
10/2/2020    113.019997
                ...
9/22/2021    145.850006
9/23/2021    146.830002
9/24/2021    146.919998
9/27/2021    145.369995
9/28/2021    142.359894
Name: Close, Length: 253, dtype: float64

**Exercise:** What was the lowest price of Apple stock for this time range? The highest? The average price?

In [46]:
### ENTER CODE HERE ###
print(f'lowest price: {round(apple.min(), 2)}')
print(f'highest price: {apple.max()}')
print(f'avg price: {apple.mean()}')

lowest price: 108.77
highest price: 156.690002
avg price: 131.12225250592886

**Exercise:** Try to select AAPL through AMZN from `ser`. What happens?

In [ ]:
### ENTER CODE HERE ###
ser['AAPL': 'AMZN']

**Exercise:** Sort the index of `ser`. Then try indexing AAPL through AMZN again.

In [48]:
### ENTER CODE HERE ###
ser = ser.sort_index()

ser['AAPL': 'AMZN']

Stock  Date
AAPL   1/11/2021     128.979996
       1/12/2021     128.800003
       1/13/2021     130.889999
       1/14/2021     128.910004
       1/15/2021     127.139999
                       ...
AMZN   9/3/2021     3478.050049
       9/30/2020    3148.729980
       9/7/2021     3509.290039
       9/8/2021     3525.500000
       9/9/2021     3484.159912
Name: Close, Length: 759, dtype: float64

**Exercise:** Select only the data for Bank of America (BAC) and Wells Fargo (WFC) from `ser`.

In [50]:
### ENTER CODE HERE ###
ser.loc[['BAC', 'WFC']]

Stock  Date
BAC    1/11/2021    33.070000
       1/12/2021    33.660000
       1/13/2021    33.459999
       1/14/2021    33.990002
       1/15/2021    33.009998
                      ...
WFC    9/3/2021     44.169998
       9/30/2020    23.510000
       9/7/2021     44.310001
       9/8/2021     43.820000
       9/9/2021     44.360001
Name: Close, Length: 506, dtype: float64

**Exercise:** Select only the data from 1/15/2021 for each stock from `ser`.

In [52]:
### ENTER CODE HERE ###
ser.loc[: , '1/15/2021']

Stock
AAPL     127.139999
AMD       88.209999
AMZN    3104.250000
BAC       33.009998
MSFT     212.649994
WFC       32.040001
Name: Close, dtype: float64

**Exercise:** Use the unstack method to turn `ser` into a DataFrame where every date is a column.

In [54]:
### ENTER CODE HERE ###
ser.unstack()

Date,1/11/2021,1/12/2021,1/13/2021,1/14/2021,1/15/2021,1/19/2021,1/20/2021,1/21/2021,1/22/2021,1/25/2021,...,9/24/2021,9/27/2021,9/28/2020,9/28/2021,9/29/2020,9/3/2021,9/30/2020,9/7/2021,9/8/2021,9/9/2021
Stock,,,,,,,,,,,,,,,,,,,,,
AAPL,128.979996,128.800003,130.889999,128.910004,127.139999,127.830002,132.029999,136.869995,139.070007,142.919998,...,146.919998,145.369995,114.959999,142.359894,114.089996,154.300003,115.809998,156.690002,155.110001,154.070007
AMD,97.250000,95.360001,91.779999,90.790001,88.209999,89.449997,88.750000,91.529999,92.790001,94.129997,...,105.800003,108.160004,79.480003,102.495003,81.769997,109.919998,81.989998,109.150002,106.169998,106.150002
AMZN,3114.209961,3120.830078,3165.889893,3127.469971,3104.250000,3120.760010,3263.379883,3306.989990,3292.229980,3294.000000,...,3425.520020,3405.800049,3174.050049,3314.500000,3144.879883,3478.050049,3148.729980,3509.290039,3525.500000,3484.159912
BAC,33.070000,33.660000,33.459999,33.990002,33.009998,32.770000,32.340000,31.770000,31.549999,31.160000,...,42.139999,43.259998,24.090000,43.345001,23.770000,41.049999,24.090000,41.320000,40.779999,40.930000
MSFT,217.490005,214.929993,216.339996,213.020004,212.649994,216.440002,224.339996,224.970001,225.949997,229.529999,...,299.350006,294.170013,209.440002,285.869995,207.259995,301.140015,210.330002,300.179993,300.209991,297.250000
WFC,33.240002,33.939999,33.799999,34.750000,32.040001,32.630001,32.459999,32.000000,31.900000,32.240002,...,47.919998,47.560001,23.820000,45.830002,23.260000,44.169998,23.510000,44.310001,43.820000,44.360001

## Multi-Index on either axis

With a DataFrame, either axis can have a hierarchical index. Let's look at a simple DataFrame to see what we mean.

In [56]:
# set up a sample DataFrame
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
    columns=[['Ohio', 'Ohio', 'Colorado'],
    ['Green', 'Red', 'Green']])

frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

Notice that Ohio has two columns associated with it while Colorado has only one.

Let's add a name to both the index and the columns.

In [58]:
# add index and column names
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

Similar to the Series example above, you can use partial column indexing to select a group of columns.

In [60]:
# select all of Ohio's data
frame['Ohio']

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

Pandas makes it easy to rearrange the order of the levels on an axis. Use `swaplevel()` to return a new object with the levels interchanged (but the data remains unaltered).

In [62]:
# swap levels
frame.swaplevel('key1','key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [64]:
# swap levels in the column
frame.swaplevel('state','color', axis=1)

color     Green  Red    Green
state      Ohio Ohio Colorado
key1 key2
a    1        0    1        2
     2        3    4        5
b    1        6    7        8
     2        9   10       11

As with our Series example above, you can use `sort_index()` to sort the indicated level.

In [66]:
# sort based on key2
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [68]:
# swap levels and sort on key2
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

#### Student Practice
Try to perform the following tasks on the `stock` dataset. Then check your answers as I walk through the solutions.

**Exercise:** Add 'ticker' and 'day' as index names to the `stock` DataFrame.

In [74]:
### ENTER CODE HERE ###
stock.index.names = ['ticker', 'day']
stock

                         Open         High          Low        Close  \
ticker day
AMZN   9/28/2020  3148.850098  3175.040039  3117.169922  3174.050049
       9/29/2020  3175.389893  3188.260010  3132.540039  3144.879883
       9/30/2020  3141.139893  3212.879883  3133.989990  3148.729980
       10/1/2020  3208.000000  3224.000000  3172.000000  3221.260010
       10/2/2020  3153.629883  3195.800049  3123.000000  3125.000000
...                       ...          ...          ...          ...
WFC    9/22/2021    46.490002    47.689999    46.470001    47.080002
       9/23/2021    47.459999    48.169998    47.160000    47.799999
       9/24/2021    47.779999    48.570000    47.730000    47.919998
       9/27/2021    48.380001    48.939999    46.160000    47.560001
       9/28/2021    47.009998    47.020000    45.070000    45.830002

                    Adj Close    Volume
ticker day
AMZN   9/28/2020  3174.050049   4224200
       9/29/2020  3144.879883   3495800
       9/30/2020  3148.729980   4896100
       10/1/2020  3221.260010   4971900
       10/2/2020  3125.000000   5613100
...                       ...       ...
WFC    9/22/2021    47.080002  29430700
       9/23/2021    47.799999  21852800
       9/24/2021    47.919998  20376800
       9/27/2021    47.560001  48916600
       9/28/2021    45.830002  31655841

[1518 rows x 6 columns]

**Exercise:** Select only the `AMZN` data from `stock`.

In [80]:
### ENTER CODE HERE ###
stock.loc['AMZN']

,Open,High,Low,Close,Adj Close,Volume
day,,,,,,
9/28/2020,3148.850098,3175.040039,3117.169922,3174.050049,3174.050049,4224200
9/29/2020,3175.389893,3188.260010,3132.540039,3144.879883,3144.879883,3495800
9/30/2020,3141.139893,3212.879883,3133.989990,3148.729980,3148.729980,4896100
10/1/2020,3208.000000,3224.000000,3172.000000,3221.260010,3221.260010,4971900
10/2/2020,3153.629883,3195.800049,3123.000000,3125.000000,3125.000000,5613100
...,...,...,...,...,...,...
9/22/2021,3351.000000,3389.000000,3341.050049,3380.050049,3380.050049,2411400
9/23/2021,3380.050049,3428.959961,3380.050049,3416.000000,3416.000000,2379400
9/24/2021,3402.010010,3429.260010,3393.399902,3425.520020,3425.520020,2113600
9/27/2021,3371.500000,3415.570068,3339.610107,3405.800049,3405.800049,3631900
9/28/2021,3357.709961,3369.189941,3290.100098,3314.500000,3314.500000,2863809

**Exercise:** Rearrange the index of the `stock` DataFrame so that `day` is first and `ticker` is second. Save this back to the `stock` DataFrame.

In [98]:
### ENTER CODE HERE ###
#frame.swaplevel('key1','key2')
stock = stock.swaplevel('day', 'ticker')
stock

,,Open,High,Low,Close,Adj Close,Volume
day,ticker,,,,,,
2020-09-28,AMZN,3148.850098,3175.040039,3117.169922,3174.050049,3174.050049,4224200
2020-09-29,AMZN,3175.389893,3188.260010,3132.540039,3144.879883,3144.879883,3495800
2020-09-30,AMZN,3141.139893,3212.879883,3133.989990,3148.729980,3148.729980,4896100
2020-10-01,AMZN,3208.000000,3224.000000,3172.000000,3221.260010,3221.260010,4971900
2020-10-02,AMZN,3153.629883,3195.800049,3123.000000,3125.000000,3125.000000,5613100
...,...,...,...,...,...,...,...
2021-09-22,WFC,46.490002,47.689999,46.470001,47.080002,47.080002,29430700
2021-09-23,WFC,47.459999,48.169998,47.160000,47.799999,47.799999,21852800
2021-09-24,WFC,47.779999,48.570000,47.730000,47.919998,47.919998,20376800
2021-09-27,WFC,48.380001,48.939999,46.160000,47.560001,47.560001,48916600
2021-09-28,WFC,47.009998,47.020000,45.070000,45.830002,45.830002,31655841

**Exercise:** Sort the index by `day`. What happens? Watch the solution video to see why that might not have worked the way that you thought it would.

In [92]:
### ENTER CODE HERE ###
#stock.sort_index() #date is stored as a string in pandas

stock = pd.read_csv('stock.csv', index_col=['Stock', 'Date'], parse_dates=['Date'])

#re-run index changes and such
stock.index.names = ['ticker', 'day']
stock = stock.swaplevel('ticker', 'day')

stock

,,Open,High,Low,Close,Adj Close,Volume
day,ticker,,,,,,
2020-09-28,AMZN,3148.850098,3175.040039,3117.169922,3174.050049,3174.050049,4224200
2020-09-29,AMZN,3175.389893,3188.260010,3132.540039,3144.879883,3144.879883,3495800
2020-09-30,AMZN,3141.139893,3212.879883,3133.989990,3148.729980,3148.729980,4896100
2020-10-01,AMZN,3208.000000,3224.000000,3172.000000,3221.260010,3221.260010,4971900
2020-10-02,AMZN,3153.629883,3195.800049,3123.000000,3125.000000,3125.000000,5613100
...,...,...,...,...,...,...,...
2021-09-22,WFC,46.490002,47.689999,46.470001,47.080002,47.080002,29430700
2021-09-23,WFC,47.459999,48.169998,47.160000,47.799999,47.799999,21852800
2021-09-24,WFC,47.779999,48.570000,47.730000,47.919998,47.919998,20376800
2021-09-27,WFC,48.380001,48.939999,46.160000,47.560001,47.560001,48916600
2021-09-28,WFC,47.009998,47.020000,45.070000,45.830002,45.830002,31655841

In [94]:
##sort index again
stock.sort_index()
stock

,,Open,High,Low,Close,Adj Close,Volume
day,ticker,,,,,,
2020-09-28,AMZN,3148.850098,3175.040039,3117.169922,3174.050049,3174.050049,4224200
2020-09-29,AMZN,3175.389893,3188.260010,3132.540039,3144.879883,3144.879883,3495800
2020-09-30,AMZN,3141.139893,3212.879883,3133.989990,3148.729980,3148.729980,4896100
2020-10-01,AMZN,3208.000000,3224.000000,3172.000000,3221.260010,3221.260010,4971900
2020-10-02,AMZN,3153.629883,3195.800049,3123.000000,3125.000000,3125.000000,5613100
...,...,...,...,...,...,...,...
2021-09-22,WFC,46.490002,47.689999,46.470001,47.080002,47.080002,29430700
2021-09-23,WFC,47.459999,48.169998,47.160000,47.799999,47.799999,21852800
2021-09-24,WFC,47.779999,48.570000,47.730000,47.919998,47.919998,20376800
2021-09-27,WFC,48.380001,48.939999,46.160000,47.560001,47.560001,48916600
2021-09-28,WFC,47.009998,47.020000,45.070000,45.830002,45.830002,31655841

## Summary Statistics by Level

Many descriptive and summary statistics on DataFrames and Series used to have a level option in which you could have specified the level you wanted to aggregate by on a particular axis. However, this is deprecated and has been removed in recent versions of Pandas. Instead, you should use `groupby`.

In [100]:
# view 'frame' DataFrame
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [104]:
# old way - will create error
#frame.sum(level='key2')

In [106]:
# current way
frame.groupby(level='key2').sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [108]:
### DEPRECATED ###

# using groupby on column axis
frame.groupby(level='color', axis=1).sum()

/var/folders/bn/mf995m8j15s64ffx8y6tfrrjfpjs54/T/ipykernel_89394/3539756321.py:4: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level='color', axis=1).sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [110]:
### UPDATED ###

# using groupby on column axis
frame.T.groupby(level='color').sum().T

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

## Indexing with DataFrame Columns
Sometimes you may want to use one or more columns from a DataFrame as the row index. Or you may wish to move the row index into the DataFrame's columns. Here's an example DataFrame.

In [112]:
# indexing with DataFrame columns
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
    'c': ['one', 'one', 'one', 'two', 'two',
    'two', 'two'],
    'd': [0, 1, 2, 0, 1, 2, 3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

Pandas `set_index()` function allows you to use one or more columns as the index.

In [114]:
# column 'c' and 'd' as the index
frame2 = frame.set_index(['c','d'])
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

This automatically drops the respective columns from the DataFrame. If you want to keep them, you can pass `drop=False` as an argument.

In [116]:
# make 'c' and 'd' index but keep in columns
frame.set_index(['c', 'd'], drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

To remove the index levels, you can use `reset_index()`, which is the opposite of `set_index()`.

In [118]:
# remove multi-index
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

#### Student Practice
Try to perform the following tasks on the `stock` dataset. Then check your answers as I walk through the solutions.

**Exercise:** Create a new column called `gain_loss` that is the difference between the closing price and opening price of the stock for each respective day.

In [160]:
### ENTER CODE HERE ###

stock['gain_loss'] = stock['Close']-stock['Open']
stock

,,Open,High,Low,Close,Adj Close,Volume,gain_loss,up_down
day,ticker,,,,,,,,
2020-09-28,AMZN,3148.850098,3175.040039,3117.169922,3174.050049,3174.050049,4224200,25.199951,down
2020-09-29,AMZN,3175.389893,3188.260010,3132.540039,3144.879883,3144.879883,3495800,-30.510010,up
2020-09-30,AMZN,3141.139893,3212.879883,3133.989990,3148.729980,3148.729980,4896100,7.590087,down
2020-10-01,AMZN,3208.000000,3224.000000,3172.000000,3221.260010,3221.260010,4971900,13.260010,down
2020-10-02,AMZN,3153.629883,3195.800049,3123.000000,3125.000000,3125.000000,5613100,-28.629883,up
...,...,...,...,...,...,...,...,...,...
2021-09-22,WFC,46.490002,47.689999,46.470001,47.080002,47.080002,29430700,0.590000,down
2021-09-23,WFC,47.459999,48.169998,47.160000,47.799999,47.799999,21852800,0.340000,down
2021-09-24,WFC,47.779999,48.570000,47.730000,47.919998,47.919998,20376800,0.139999,down
2021-09-27,WFC,48.380001,48.939999,46.160000,47.560001,47.560001,48916600,-0.820000,up
2021-09-28,WFC,47.009998,47.020000,45.070000,45.830002,45.830002,31655841,-1.179996,up

**Exercise:** What is the average gain or loss per stock?

In [162]:
### ENTER CODE HERE ###
round(stock['gain_loss'].mean(),2)


##prof solution
stock.groupby('ticker')['gain_loss'].mean()

ticker
AAPL   -0.002096
AMD    -0.058775
AMZN   -2.824046
BAC     0.037886
MSFT    0.180414
WFC     0.048459
Name: gain_loss, dtype: float64

**Exercise:** What is the total gain or loss sum per stock?

In [164]:
### ENTER CODE HERE ###
stock.groupby(level='ticker').sum('gain_loss')

##
stock.groupby('ticker')['gain_loss'].sum()

ticker
AAPL     -0.530267
AMD     -14.869989
AMZN   -714.483652
BAC       9.585032
MSFT     45.644855
WFC      12.260029
Name: gain_loss, dtype: float64

**Exercise:** Remove the multi-index from the `stock` DataFrame and save this back.

In [166]:
### ENTER CODE HERE ###
stock = stock.reset_index()
stock

,day,ticker,Open,High,Low,Close,Adj Close,Volume,gain_loss,up_down
0,2020-09-28,AMZN,3148.850098,3175.040039,3117.169922,3174.050049,3174.050049,4224200,25.199951,down
1,2020-09-29,AMZN,3175.389893,3188.260010,3132.540039,3144.879883,3144.879883,3495800,-30.510010,up
2,2020-09-30,AMZN,3141.139893,3212.879883,3133.989990,3148.729980,3148.729980,4896100,7.590087,down
3,2020-10-01,AMZN,3208.000000,3224.000000,3172.000000,3221.260010,3221.260010,4971900,13.260010,down
4,2020-10-02,AMZN,3153.629883,3195.800049,3123.000000,3125.000000,3125.000000,5613100,-28.629883,up
...,...,...,...,...,...,...,...,...,...,...
1513,2021-09-22,WFC,46.490002,47.689999,46.470001,47.080002,47.080002,29430700,0.590000,down
1514,2021-09-23,WFC,47.459999,48.169998,47.160000,47.799999,47.799999,21852800,0.340000,down
1515,2021-09-24,WFC,47.779999,48.570000,47.730000,47.919998,47.919998,20376800,0.139999,down
1516,2021-09-27,WFC,48.380001,48.939999,46.160000,47.560001,47.560001,48916600,-0.820000,up
1517,2021-09-28,WFC,47.009998,47.020000,45.070000,45.830002,45.830002,31655841,-1.179996,up

**Exercise:** Create a new column called `up_down` that tells you whether the stock finished up for the day or down.

In [170]:
### ENTER CODE HERE ###
stock['up_down'] = stock['gain_loss'].apply(lambda x: 'up' if x > 0 else 'down')


##prof solution
mapping = {-1: 'Down', 1: 'Up'}
stock['up_down'] = np.sign(stock['gain_loss']).map(mapping)
stock

,day,ticker,Open,High,Low,Close,Adj Close,Volume,gain_loss,up_down
0,2020-09-28,AMZN,3148.850098,3175.040039,3117.169922,3174.050049,3174.050049,4224200,25.199951,Up
1,2020-09-29,AMZN,3175.389893,3188.260010,3132.540039,3144.879883,3144.879883,3495800,-30.510010,Down
2,2020-09-30,AMZN,3141.139893,3212.879883,3133.989990,3148.729980,3148.729980,4896100,7.590087,Up
3,2020-10-01,AMZN,3208.000000,3224.000000,3172.000000,3221.260010,3221.260010,4971900,13.260010,Up
4,2020-10-02,AMZN,3153.629883,3195.800049,3123.000000,3125.000000,3125.000000,5613100,-28.629883,Down
...,...,...,...,...,...,...,...,...,...,...
1513,2021-09-22,WFC,46.490002,47.689999,46.470001,47.080002,47.080002,29430700,0.590000,Up
1514,2021-09-23,WFC,47.459999,48.169998,47.160000,47.799999,47.799999,21852800,0.340000,Up
1515,2021-09-24,WFC,47.779999,48.570000,47.730000,47.919998,47.919998,20376800,0.139999,Up
1516,2021-09-27,WFC,48.380001,48.939999,46.160000,47.560001,47.560001,48916600,-0.820000,Down
1517,2021-09-28,WFC,47.009998,47.020000,45.070000,45.830002,45.830002,31655841,-1.179996,Down

**Exercise:** Set the level 0 index as `ticker` and the level 1 index as `up_down`. Sort index by `ticker`. Save these changes back to the `stock` DataFrame.

In [172]:
### ENTER CODE HERE ###
stock= stock.set_index(['ticker', 'up_down']).sort_index()
stock

                      day        Open        High         Low       Close  \
ticker up_down
AAPL   Down    2020-09-28  115.010002  115.320000  112.779999  114.959999
       Down    2020-09-29  114.550003  115.309998  113.570000  114.089996
       Down    2020-10-01  117.639999  117.720001  115.830002  116.790001
       Down    2020-10-06  115.699997  116.120003  112.250000  113.160004
       Down    2020-10-08  116.250000  116.400002  114.589996  114.970001
...                   ...         ...         ...         ...         ...
WFC    Up      2021-09-17   45.740002   46.689999   45.740002   46.470001
       Up      2021-09-20   45.029999   45.869999   44.840000   45.810001
       Up      2021-09-22   46.490002   47.689999   46.470001   47.080002
       Up      2021-09-23   47.459999   48.169998   47.160000   47.799999
       Up      2021-09-24   47.779999   48.570000   47.730000   47.919998

                 Adj Close     Volume  gain_loss
ticker up_down
AAPL   Down     114.225311  137672400  -0.050003
       Down     113.360878   99382200  -0.460007
       Down     116.043625  116120400  -0.849998
       Down     112.436829  161498200  -2.539993
       Down     114.235260   83477200  -1.279999
...                    ...        ...        ...
WFC    Up        46.470001   34912100   0.729999
       Up        45.810001   30603100   0.780002
       Up        47.080002   29430700   0.590000
       Up        47.799999   21852800   0.340000
       Up        47.919998   20376800   0.139999

[1518 rows x 8 columns]

**Exercise:** How many days were up and how many days were down per stock? Which stock had the most days down? Which stock had the most days up?

In [176]:
### ENTER CODE HERE ###
stock.groupby(['ticker', 'up_down'])['day'].count()

ticker  up_down
AAPL    Down       130
        Up         123
AMD     Down       137
        Up         116
AMZN    Down       130
        Up         122
BAC     Down       104
        Up         149
MSFT    Down       116
        Up         136
WFC     Down       127
        Up         126
Name: day, dtype: int64

**Exercise:** Add together the total trading volume by stock and sort from highest volume to the lowest volume for the DataFrame.

In [180]:
### ENTER CODE HERE ###

stock.groupby('ticker')['Volume'].sum().sort_values(ascending=False)

ticker
AAPL    24628086996
BAC     12982658321
AMD     12404431707
WFC      8231317141
MSFT     6715505055
AMZN      940146109
Name: Volume, dtype: int64

**Exercise:** Add a new column called `range` that shows the difference between the highest price and the lowest price for each day.

In [182]:
### ENTER CODE HERE ###s
stock['range'] = stock['High'] - stock['Low']
stock.groupby('ticker')['range'].min()

ticker
AAPL     0.970001
AMD      0.959999
AMZN    22.189941
BAC      0.279998
MSFT     1.759979
WFC      0.340000
Name: range, dtype: float64

In [184]:
stock.groupby('ticker')['range'].max()

ticker
AAPL      8.550003
AMD       9.159996
AMZN    239.659912
BAC       2.379997
MSFT     10.300003
WFC       3.780003
Name: range, dtype: float64

In [186]:
stock.groupby('ticker')['range'].median()

ticker
AAPL     2.560005
AMD      2.580001
AMZN    60.969971
BAC      0.729999
MSFT     3.689988
WFC      0.949997
Name: range, dtype: float64

**Exercise:** Answer the following questions:
- What stock had the lowest trading range for a specific day?
- What stock had the highest trading range for a specific day?
- What was the median trading range per stock?
- What was the average trading range per stock?

In [ ]:
### ENTER CODE HERE ###