In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Create a simple Dataframe going from 0 to 29
data = pd.DataFrame({'values':range(0,30)})

In [12]:
data

    values
0        0
1        1
2        2
3        3
4        4
5        5
6        6
7        7
8        8
9        9
10      10
11      11
12      12
13      13
14      14
15      15
16      16
17      17
18      18
19      19
20      20
21      21
22      22
23      23
24      24
25      25
26      26
27      27
28      28
29      29

In [10]:
#bins 0-10;11-25;>25
bins = [0,10,25,100]

# These will create the bins:
# (0,10) - with the low part not Inclusive; high part inclusive; going from 1 to 10
# (10,25) - with the low part not Inclusive; high part inclusive; going from 11 to 25
# (25,100) - with the low part not Inclusive; high part inclusive; going from 26 to 99

data['my_bins'] = pd.cut(data['values'],bins)
data

    values       my_bins
0        0           NaN
1        1   (0.0, 10.0]
2        2   (0.0, 10.0]
3        3   (0.0, 10.0]
4        4   (0.0, 10.0]
5        5   (0.0, 10.0]
6        6   (0.0, 10.0]
7        7   (0.0, 10.0]
8        8   (0.0, 10.0]
9        9   (0.0, 10.0]
10      10   (0.0, 10.0]
11      11  (10.0, 25.0]
12      12  (10.0, 25.0]
13      13  (10.0, 25.0]
14      14  (10.0, 25.0]
15      15  (10.0, 25.0]
16      16  (10.0, 25.0]
17      17  (10.0, 25.0]
18      18  (10.0, 25.0]
19      19  (10.0, 25.0]
20      20  (10.0, 25.0]
21      21  (10.0, 25.0]
22      22  (10.0, 25.0]
23      23  (10.0, 25.0]
24      24  (10.0, 25.0]

In [24]:
#bins 0-10;11-25;>25
bins = [-1,10,25,100]

# These will create the bins:
# (-1,10) - with the low part not Inclusive; high part inclusive; going from 0 to 10
# (10,25) - with the low part not Inclusive; high part inclusive; going from 11 to 25
# (25,100) - with the low part not Inclusive; high part inclusive; going from 26 to 99

data['my_bins'] = pd.cut(data['values'],bins,)
data

    values    my_bins
0        0   (-1, 10]
1        1   (-1, 10]
2        2   (-1, 10]
3        3   (-1, 10]
4        4   (-1, 10]
5        5   (-1, 10]
6        6   (-1, 10]
7        7   (-1, 10]
8        8   (-1, 10]
9        9   (-1, 10]
10      10   (-1, 10]
11      11   (10, 25]
12      12   (10, 25]
13      13   (10, 25]
14      14   (10, 25]
15      15   (10, 25]
16      16   (10, 25]
17      17   (10, 25]
18      18   (10, 25]
19      19   (10, 25]
20      20   (10, 25]
21      21   (10, 25]
22      22   (10, 25]
23      23   (10, 25]
24      24   (10, 25]
25      25   (10, 25]
26      26  (25, 100]
27      27  (25, 100]
28      28  (25, 100]
29      29  (25, 100]

In [26]:
#bins 0-10;11-25;>25
bins = [0,10,25,100]

# NOTE THE PARAMETER include_lowest=True; These will create the bins:
# (-0.0001,10) - with the low not Inclusive; high part inclusive; going from 0 to 10
# (10,25) - with the low part not Inclusive; high part inclusive; going from 11 to 25
# (20,100) - with the low part not Inclusive; high part inclusive; going from 26 to inf

data['my_bins'] = pd.cut(data['values'],bins, include_lowest=True)
data

    values         my_bins
0        0  (-0.001, 10.0]
1        1  (-0.001, 10.0]
2        2  (-0.001, 10.0]
3        3  (-0.001, 10.0]
4        4  (-0.001, 10.0]
5        5  (-0.001, 10.0]
6        6  (-0.001, 10.0]
7        7  (-0.001, 10.0]
8        8  (-0.001, 10.0]
9        9  (-0.001, 10.0]
10      10  (-0.001, 10.0]
11      11    (10.0, 25.0]
12      12    (10.0, 25.0]
13      13    (10.0, 25.0]
14      14    (10.0, 25.0]
15      15    (10.0, 25.0]
16      16    (10.0, 25.0]
17      17    (10.0, 25.0]
18      18    (10.0, 25.0]
19      19    (10.0, 25.0]
20      20    (10.0, 25.0]
21      21    (10.0, 25.0]
22      22    (10.0, 25.0]
23      23    (10.0, 25.0]
24      24    (10.0, 25.0]
25      25    (10.0, 25.0]
26      26   (25.0, 100.0]
27      27   (25.0, 100.0]
28      28   (25.0, 100.0]
29      29   (25.0, 100.0]

In [29]:
#bins 0-10;11-25;>25
bins = [np.NINF ,10,25,np.inf]

# NOTE THE VALUES np.NINF (negative infinity) and the np.inf (positive infinity); These will create the bins:
# (-inf,10) - with the low part not Inclusive; high part inclusive; going from -inf to 10
# (10,25) - with the low part not Inclusive; high part inclusive; going from 11 to 25
# (20,inf) - with the low part not Inclusive; high part inclusive; going from 26 to inf

data['my_bins'] = pd.cut(data['values'],bins)
data

    values       my_bins
0        0  (-inf, 10.0]
1        1  (-inf, 10.0]
2        2  (-inf, 10.0]
3        3  (-inf, 10.0]
4        4  (-inf, 10.0]
5        5  (-inf, 10.0]
6        6  (-inf, 10.0]
7        7  (-inf, 10.0]
8        8  (-inf, 10.0]
9        9  (-inf, 10.0]
10      10  (-inf, 10.0]
11      11  (10.0, 25.0]
12      12  (10.0, 25.0]
13      13  (10.0, 25.0]
14      14  (10.0, 25.0]
15      15  (10.0, 25.0]
16      16  (10.0, 25.0]
17      17  (10.0, 25.0]
18      18  (10.0, 25.0]
19      19  (10.0, 25.0]
20      20  (10.0, 25.0]
21      21  (10.0, 25.0]
22      22  (10.0, 25.0]
23      23  (10.0, 25.0]
24      24  (10.0, 25.0]
25      25  (10.0, 25.0]
26      26   (25.0, inf]
27      27   (25.0, inf]
28      28   (25.0, inf]
29      29   (25.0, inf]

In [33]:
#bins 0-10;11-25;>25
bins = [np.NINF ,10,25,np.inf]

# NOTE THE VALUES np.NINF (negative infinity) and the np.inf (positive infinity); These will create the bins:
# (-inf,10) - with the low part not Inclusive; high part inclusive; going from -inf to 10
# (10,25) - with the low part not Inclusive; high part inclusive; going from 11 to 25
# (20,inf) - with the low part not Inclusive; high part inclusive; going from 26 to inf

data['my_bins'] = pd.cut(data['values'],bins, labels=['0-10','11-25','>25'])
data

    values my_bins
0        0    0-10
1        1    0-10
2        2    0-10
3        3    0-10
4        4    0-10
5        5    0-10
6        6    0-10
7        7    0-10
8        8    0-10
9        9    0-10
10      10    0-10
11      11   11-25
12      12   11-25
13      13   11-25
14      14   11-25
15      15   11-25
16      16   11-25
17      17   11-25
18      18   11-25
19      19   11-25
20      20   11-25
21      21   11-25
22      22   11-25
23      23   11-25
24      24   11-25
25      25   11-25
26      26     >25
27      27     >25
28      28     >25
29      29     >25

In [39]:
#bins 0-10;11-25;>25
bins = [0,11,26,np.inf]

# NOTE THE right=False; This makes the low part INCLUSIVE and the High part NOT INCLUSIVE
# (0,11) - with the low part INCLUSIVE; high part NOT inclusive; going from 0 to 10
# (11,26) - with the low part INCLUSIVE; high part NOT inclusive; going from 11 to 25
# (26,inf) - with the low part INCLUSIVE; high part NOT inclusive; going from 26 to inf

data['my_bins'] = pd.cut(data['values'],bins, right=False)
data

    values       my_bins
0        0   [0.0, 11.0)
1        1   [0.0, 11.0)
2        2   [0.0, 11.0)
3        3   [0.0, 11.0)
4        4   [0.0, 11.0)
5        5   [0.0, 11.0)
6        6   [0.0, 11.0)
7        7   [0.0, 11.0)
8        8   [0.0, 11.0)
9        9   [0.0, 11.0)
10      10   [0.0, 11.0)
11      11  [11.0, 26.0)
12      12  [11.0, 26.0)
13      13  [11.0, 26.0)
14      14  [11.0, 26.0)
15      15  [11.0, 26.0)
16      16  [11.0, 26.0)
17      17  [11.0, 26.0)
18      18  [11.0, 26.0)
19      19  [11.0, 26.0)
20      20  [11.0, 26.0)
21      21  [11.0, 26.0)
22      22  [11.0, 26.0)
23      23  [11.0, 26.0)
24      24  [11.0, 26.0)
25      25  [11.0, 26.0)
26      26   [26.0, inf)
27      27   [26.0, inf)
28      28   [26.0, inf)
29      29   [26.0, inf)

In [40]:
#bins 0-10;11-25;>25
bins = [0,11,26,np.inf]

# NOTE THE right=False; This makes the low part INCLUSIVE and the High part NOT INCLUSIVE
# (0,11) - with the low part INCLUSIVE; high part NOT inclusive; going from 0 to 10
# (11,26) - with the low part INCLUSIVE; high part NOT inclusive; going from 11 to 25
# (26,inf) - with the low part INCLUSIVE; high part NOT inclusive; going from 26 to 100

data['my_bins'] = pd.cut(data['values'],bins, labels=['0-10','11-25','>25'], right=False)
data

    values my_bins
0        0    0-10
1        1    0-10
2        2    0-10
3        3    0-10
4        4    0-10
5        5    0-10
6        6    0-10
7        7    0-10
8        8    0-10
9        9    0-10
10      10    0-10
11      11   11-25
12      12   11-25
13      13   11-25
14      14   11-25
15      15   11-25
16      16   11-25
17      17   11-25
18      18   11-25
19      19   11-25
20      20   11-25
21      21   11-25
22      22   11-25
23      23   11-25
24      24   11-25
25      25   11-25
26      26     >25
27      27     >25
28      28     >25
29      29     >25